class ErrorCodes:
    DATABASE_CONNECTION_FAILED = "DATABASE_CONNECTION_FAILED"
    CHUNK_EXECUTION_FAILED = "CHUNK_EXECUTION_FAILED"
    JOB_NOT_FOUND = "JOB_NOT_FOUND"
    TABLE_NOT_FOUND = "TABLE_NOT_FOUND"
    INVALID_MAPPING = "INVALID_MAPPING"
